-
  name: 'Skynet Accessibility Admin API'
  uriPattern: 'api/skynetaccessibilityscanner/admin-info'
  defaults:
    '@package': 'Skynettechnologies.Skynetaccessibilityscanner'
    '@controller': 'AdminApi'
    '@action': 'info'
